#!/bin/bash

P_NAME=$1
mkdir $P_NAME
cd $P_NAME
cp /opt/cp-utils/contest-creator/template.cpp sol.cpp
cp /opt/cp-utils/contest-creator/template.cpp brute.cpp
cp /opt/cp-utils/contest-creator/gen.cpp gen.cpp
cp /opt/cp-utils/contest-creator/run_tests.sh run_tests.sh
touch in
touch out
cd ..
